
print.simplejags <- function(x,digits=3){
  if(!x$bugs.format){
  cat('JAGS output for model \'',x$modfile,'\', generated by simplejags.','\n',sep="")
  cat('Estimates based on',round(x$mcmc.info[[1]],0),'chains of',round(x$mcmc.info[[3]],0),'iterations,') 
  cat(' burn-in = ',round(x$mcmc.info[[4]],0),' and thin rate = ',round(x$mcmc.info[[5]],0),',','\n',sep="")
  cat('yielding',round(x$mcmc.info[[6]],0),'total samples from the joint posterior.','\n')
  cat('MCMC ran for ',x$mcmc.info[[7]],' minutes at time ',paste(x$run.date),'.\n','\n',sep="")

  y = data.frame(unlist(x$mean),unlist(x$sd),unlist(x$q2.5),unlist(x$q50),unlist(x$q97.5),
                 unlist(x$overlap0),unlist(x$f),unlist(x$Rhat),unlist(x$n.eff)) 
  row.names(y) = colnames(x$samples[[1]])
  names(y) = c('mean','sd','2.5%','50%','97.5%','overlap0','f','Rhat','n.eff')
  if(x$mcmc.info[[1]]==1){
  y = y[,-c(8,9)]
  }
  #get the rounding to look clean, move deviance to bottom
  z <-  as.data.frame(round(as.matrix(y),digits))
  z[,6] <- z[,6]==1
  print(z)
  
  cat('\noverlap0 indicates if 0 falls within the 95% credible interval for the parameter.\n')
  cat('f represents the proportion of a parameter\'s posterior distribution with the same\n')
  cat('sign as the mean; i.e., our confidence that the parameter is positive or negative.\n')
  
  if(x$mcmc.info[[1]]>1){
  if(max(unlist(x$Rhat))>1.1){cat('\n**WARNING** Rhat values indicate convergence failure.','\n')
  }else{cat('\nSuccessful convergence based on Rhat values (all < 1.1).','\n')}
  cat('Rhat is the potential scale reduction factor (at convergence, Rhat=1).','\n')
  cat('For each parameter, n.eff is a crude measure of effective sample size.','\n')
  }
  
  if(!is.null(x$DIC)){
    
    cat('\nDIC info: (pD = var(deviance)/2)','\npD =',round(x$pD,1),'and DIC =',round(x$DIC,digits),'\n')
    cat('DIC is an estimate of expected predictive error (lower is better).\n')
    
  }
  } else {print.simplebugs(x,digits=digits)}
}