
print.simplejags <- function(x,digits=3){
  cat('JAGS output for model \'',x$modfile,'\', generated by simplejags()','\n',sep="")
  cat('Estimates based on',round(x$mcmc.info[[1]],0),'chains of',round(x$mcmc.info[[3]],0),'iterations,') 
  cat(' burn-in = ',round(x$mcmc.info[[4]],0),' and thin rate = ',round(x$mcmc.info[[5]],0),':','\n',sep="")
  cat(round(x$mcmc.info[[6]],0),'total samples from the joint posterior','\n')
  cat('MCMC ran for',x$mcmc.info[[7]],'minutes at time',paste(x$run.date),'\n','\n')
  if(x$mcmc.info[[1]]>1){
  y = data.frame(x$mean,x$se,x$q2.5,x$q50,x$q97.5,x$overlap0,x$f,x$Rhat,x$n.eff)
  names(y) = c('Mean','SE','2.5%','50%','97.5%','0inCI?','f','Rhat','n.eff')
  } else {
  y = data.frame(x$mean,x$se,x$q2.5,x$q50,x$q97.5,x$overlap0,x$f)
  names(y) = c('Mean','SE','2.5%','50%','97.5%','0inCI?','f')  
  }
  print(y,digits=digits)
}